### ISSUE TITLE
Include functions from the Collisions API

### ISSUE THREAD

**Issue by APXEOLOG** [ice1000/gdx-box2d#1]
Hello, can we add binding for some functions available in the Box2D Collision API?

I'm specifically interested in [b2TestOverlap](https://box2d.org/documentation/b2__collision_8h.html#a769992d82855399cf20721cd6b411fe7), but there are many functions out there that are useful as well.

**Comment by ice1000** [comment]
Which overload are you specifically interested in?

**Comment by APXEOLOG** [comment]
For my project it would be useful to have access to the following functions:


`b2TestOverlap` from `b2_collision.h`
```cpp
b2TestOverlap (const b2Shape *shapeA, int32 indexA, const b2Shape *shapeB, int32 indexB, const b2Transform &xfA, const b2Transform &xfB)
```
(The AABB version `bool 	b2TestOverlap (const b2AABB &a, const b2AABB &b)` can be useful as well, even though I do not have use case for it right now)

`b2Distance` from `b2_distance.h`
```cpp
B2_API void b2Distance(b2DistanceOutput* output,
                 b2SimplexCache* cache,
                 const b2DistanceInput* input);
```

**Comment by ice1000** [comment]
Working with `b2DistanceProxy` in the `b2DistanceInput` looks a bit hard, but the others are just trivial work. I'll try to do them this week.

**Comment by ice1000** [comment]
@APXEOLOG I've implemented `b2TestOverlap`. I don't want to do the AABB version because it's an inline function on C++ side, so IMO it should be implemented in Java, instead of through JNI. How do you plan to use `b2DistanceProxy`? I don't want to make too complicated interface just for `b2Distance`...

**Comment by ice1000** [comment]
So I'll avoid `b2Distance` for now, and publish a newer version. I've also updated the libgdx dependency in this project, hopefully it can be nicer this way.

**Comment by ice1000** [comment]
`com.badlogic.gdx.physics.box2d.Shape#testOverlap`

**Comment by APXEOLOG** [comment]
> @APXEOLOG I've implemented `b2TestOverlap`. I don't want to do the AABB version because it's an inline function on C++ side, so IMO it should be implemented in Java, instead of through JNI. How do you plan to use `b2DistanceProxy`? I don't want to make too complicated an interface just for `b2Distance`...

As far as I see `b2Distance` allows us to calculate the distance between the two "bodies" (shape + transform vs share + transform). This is what I intended to use it for. But it's fine without it, I did a workaround approximate implementation for now, maybe I'll look into this issue later, if I'll need an improved version.

Thank you very much for adding `b2TestOverlap`!

**Comment by ice1000** [comment]
> > @APXEOLOG I've implemented `b2TestOverlap`. I don't want to do the AABB version because it's an inline function on C++ side, so IMO it should be implemented in Java, instead of through JNI. How do you plan to use `b2DistanceProxy`? I don't want to make too complicated an interface just for `b2Distance`...
> 
> As far as I see `b2Distance` allows us to calculate the distance between the two "bodies" (shape + transform vs share + transform). This is what I intended to use it for. But it's fine without it, I did a workaround approximate implementation for now, maybe I'll look into this issue later, if I'll need an improved version.
> 
> Thank you very much for adding `b2TestOverlap`!

If you look close enough at my recent commits on adding `testOverlap` it should be fairly easy to infer how to add distance. It remains to figure out if we can just dodge those callbacks at all, and it could possibly be worked out this way. Contribution is always welcome.
